version: '3'
networks:
  avia-tickets:
services:
  tickets:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - avia-tickets
  cron:
      image: zalari/docker-cron
      volumes:
          - ./:/var/www/html
      networks:
          - avia-tickets
#      environment:
#          - |
#              DOCKER_CRONTAB=
#              30 22 * * * cd /cron-env/project && docker-compose run --rm -T dump_db_out > db_dump/`date +"%m-%d-%y"`-project.sql
#              30 22 * * * cd /cron-env/project/db_dump && find *.sql -mtime +30 -delete

  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: avia-tickets
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
    - dbdata:/var/lib/mysql
    networks:
      - avia-tickets

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: root
    ports:
      - "8888:80"
    networks:
      - avia-tickets

  php:
    build:
      context: .
      dockerfile: ./Docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - avia-tickets

  php-bot:
      build:
          context: .
          dockerfile: ./Docker/php/bot.Dockerfile
      volumes:
          - ./:/var/www/html
      networks:
          - avia-tickets

  composer:
    image: composer:latest
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php

  npm:
    image: node:latest
    container_name: tickets-npm
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm', '--no-bin-links']
    networks:
      - avia-tickets

  artisan:
    build:
      context: .
      dockerfile: ./Docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - avia-tickets

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - avia-tickets

#Volumes
volumes:
  dbdata:
    driver: local
